version: '3.7'
services:
  app:
    image: gisemartinez/challenge
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - '8080:8080'
    environment:
      - DB_SERVER=postgres
      - DB_PORT=5432
  postgres:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5438:5432'
    volumes:
      - ./resources/scripts/init_db.sql:/docker-entrypoint-initdb.d/init.sql